### ISSUE TITLE
NullPointer on Jtextfield

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/material-ui-swing#24]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mdlaf.components.textfield.MaterialTextFieldUI.propertyChange(MaterialTextFieldUI.java:244)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8428)
	at java.awt.Component.setBackground(Component.java:1835)
	at javax.swing.JComponent.setBackground(JComponent.java:2733)
	at javax.swing.plaf.basic.BasicTextUI.installDefaults(BasicTextUI.java:312)
	at javax.swing.plaf.basic.BasicTextUI.installUI(BasicTextUI.java:787)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.text.JTextComponent.setUI(JTextComponent.java:328)
	at javax.swing.text.JTextComponent.updateUI(JTextComponent.java:338)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1233)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1224)
	at SwingSet2$7.run(SwingSet2.java:1031)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mdlaf.components.textfield.MaterialTextFieldUI.propertyChange(MaterialTextFieldUI.java:244)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8428)
	at java.awt.Component.setBackground(Component.java:1835)
	at javax.swing.JComponent.setBackground(JComponent.java:2733)
	at javax.swing.plaf.basic.BasicTextUI.installDefaults(BasicTextUI.java:312)
	at javax.swing.plaf.basic.BasicTextUI.installUI(BasicTextUI.java:787)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.text.JTextComponent.setUI(JTextComponent.java:328)
	at javax.swing.text.JTextComponent.updateUI(JTextComponent.java:338)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1233)
	at javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1224)
	at javax.swing.SwingUtilities.updateRendererOrEditorUI(SwingUtilities.java:1981)
	at javax.swing.JTable.updateUI(JTable.java:3634)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1233)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1224)
	at SwingSet2$7.run(SwingSet2.java:1031)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vincenzopalazzo** [comment]
fixing in the next commit
