### ISSUE TITLE
JButton NullPointerException from timer while calling mouseEntered

### ISSUE THREAD

**Issue by kc-bam** [vincenzopalazzo/material-ui-swing#90]
Hi there. I try to use your LaF in diffrent tools, but in two of them i get a NullpointerException when I hover over a JButton. The timer object is null then. Both Buttons have the simularity that they get enabled/disabled by calling a method (for ex. it checks if a list has size > 0).  I tried to reproduce the exception in a new project without success.. any idea? thank you

**Comment by vincenzopalazzo** [comment]
Hi @kc-bam,

What is the your library version?

**Comment by kc-bam** [comment]
I am using Maven:

        <dependency>
            <groupId>io.github.vincenzopalazzo</groupId>
            <artifactId>material-ui-swing</artifactId>
            <version>1.0.6</version>
        </dependency>

**Comment by kc-bam** [comment]
Ok seems, that the highest Version in Maven Repository is v0.9.4.5

**Comment by vincenzopalazzo** [comment]
@kc-bam can you give me the exception stack? for analyzing the your error.

**Comment by kc-bam** [comment]
Sure

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mdlaf.animation.MaterialUITimer.mouseEntered(MaterialUITimer.java:152)
	at java.desktop/java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:308)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6645)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4698)
	at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4676)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4527)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)``

**Comment by vincenzopalazzo** [comment]
@kc-bam take me the time for analyzing all.

PS: you have the personal configuration of material-ui-swing?

**Comment by kc-bam** [comment]
what do you mean with personal configuration? i just inserted the maven dependency and these lines in the main:

java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
//                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    UIManager.setLookAndFeel(new MaterialLookAndFeel());
                } catch (UnsupportedLookAndFeelException e) {
                }
                MainFrame frame = MainFrame.getInstance();
                SwingUtilities.updateComponentTreeUI(frame);
            }
        });

**Comment by vincenzopalazzo** [comment]
@kc-bam thanks, give me some time to find the problem, and I will return here.

Thanks so much

**Comment by vincenzopalazzo** [comment]
@kc-bam can you do some test inside your app?

1. Why you set the look and feel inside the main?
2. Why you run this code?
```
MainFrame frame = MainFrame.getInstance();
SwingUtilities.updateComponentTreeUI(frame);
```

## My passage for your code 

1. Move the code inside static section, like this:

```
static {
    try {
      UIManager.setLookAndFeel(new MaterialLookAndFeel());
    } catch (UnsupportedLookAndFeelException e) {}
}
```

2. or If you want to use another theme you can use the code following like:
`MaterialLookAndFeel.changeTheme(new MaterialOceanicTheme());`

ps: send me the feedback when you run the passage 1.

##Not work yet?

I have the need to more information, because the object Timer is built inside the constructor, so if the timer is null the unique constructor is never called

**Comment by kc-bam** [comment]
I just deleted this line 

> SwingUtilities.updateComponentTreeUI(frame);

and it seems to work now. It was a leftover of old code.... thank you very much! ;)
but it would be interesting to know, how the time variable could be null.... maybe sth with the garbage collector?

**Comment by vincenzopalazzo** [comment]
> thank you very much! ;)

Thank you @kc-bam to using the material-ui-swing.

>it would be interesting to know, how the time variable could be null.... maybe sth with the garbage collector?

Yes, this is very strange, I don't reproduce the problem, inside the demo I will call the `SwingUtilities.updateComponentTreeUI(frame);`
[In this](https://github.com/vincenzopalazzo/material-ui-swing/releases/download/V1.0.6/Demo-Swing-set3.tar) demo work well
